### PR TITLE
Update to use Akka 1.3.1.

### PR DESCRIPTION
**Pull request by ghost**
Akka 1.3.1 was released a month ago, this change provides a corresponding version for Akka.Logger.log4net.

### CODE REVIEW

**Comment by basbossinkdivverence** [comment]
Would you also be so kind to upload the resulting nuget package to nuget? Thanks in advance.

**Comment by Aaronontheweb** [comment]
@basbossinkdivverence sure thing! We'll get that pushed.

**Comment by Aaronontheweb** [comment]
It's up now.

**Comment by ghost** [comment]
Thanks, for the quick response and action.

**Pull request merged**
